version: "3.9"
services:
  backend:
    build: ./todo-backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/tododb?schema=public"
    depends_on:
      - db

  frontend:
    build: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: "http://localhost:3000/api"

  db:
    image: postgres:16
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
